name: AVD Deployment using Terraform

on: workflow_dispatch

defaults:
  run:
    working-directory: ./terraform

jobs:
  avd-tf:
    runs-on: ubuntu-latest
    
    env:
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
  
    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Cache Terraform modules
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/terraform/.terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/main.tf') }}
          restore-keys: |
            ${{ runner.os }}-terraform-  
        
      - name: List directory
        run: ls -a

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
        
    # - name: Terraform Apply
    #   if: github.ref == 'refs/heads/main' && github.event_name == 'push' The terraform apply step is conditional (if) and only runs when the workflow is triggered by a push event on the main branch
    #   run: terraform apply -auto-approve